name: vcdub-release
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - numpy
  - pandas
  - tqdm
  - soundfile
  - librosa
  - pytorch
  - torchaudio
  - pip:
      - transformers>=4.40
      - demucs>=4.0
      - julius>=0.2.7
